### ISSUE TITLE
[Feat] - Add other encryption methods 

### ISSUE THREAD

**Issue by jenaye** [CMEPW/221b#2]
At present, the XOR method works correctly, 
but it would be interesting to implement one part for AES and another for ChaCha20.

useful implementation links :
https://pkg.go.dev/golang.org/x/crypto/chacha20
https://github.com/CMEPW/myph/blob/main/loader/aes.go

**Comment by TomChv** [comment]
Yeah! Sounds good to me! I can work on that soon

**Comment by TomChv** [comment]
@jenaye We added chacha20 et aes, is there any other method we shall add or we can close this issue for now?

**Comment by jenaye** [comment]
There are plenty of others but I think this is more than enough thanks for your work :)
